<?php

namespace Ortic\DuckDB\Console;

use Illuminate\Console\Command;

class InstallDdevCommand extends Command
{
    protected $signature = 'duckdb:install-ddev {--force : Overwrite an existing web-build Dockerfile}';

    protected $description = 'Scaffold a DDEV web-build Dockerfile that compiles pdo_duckdb into the web container';

    public function handle(): int
    {
        $ddevDir = base_path('.ddev');

        if (! is_dir($ddevDir)) {
            $this->error('No .ddev/ directory found — this does not look like a DDEV project.');
            $this->line('Run `ddev config` first, or copy the Dockerfile from the pdo_duckdb repo manually.');

            return self::FAILURE;
        }

        $target = $ddevDir.'/web-build/Dockerfile';

        if (file_exists($target) && ! $this->option('force')) {
            $this->warn('.ddev/web-build/Dockerfile already exists; leaving it untouched.');
            $this->line('Re-run with --force to overwrite, or merge the snippet from the pdo_duckdb README.');

            return self::SUCCESS;
        }

        $dir = dirname($target);
        if (! is_dir($dir) && ! mkdir($dir, 0755, true) && ! is_dir($dir)) {
            $this->error("Could not create {$dir}.");

            return self::FAILURE;
        }

        file_put_contents($target, $this->dockerfile());

        $this->info('Created .ddev/web-build/Dockerfile');
        $this->line('Next: run `ddev restart` to build pdo_duckdb into the web image.');

        return self::SUCCESS;
    }

    private function dockerfile(): string
    {
        // nowdoc: the ${...} and $(...) below are Docker/shell, not PHP.
        return <<<'DOCKER'
# Builds the pdo_duckdb extension into the DDEV web container.
# Generated by `php artisan duckdb:install-ddev`.
#
# Pin the DuckDB release with:
#   ddev config --web-environment-add=DUCKDB_VERSION=v1.5.4
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG DUCKDB_VERSION=v1.5.4

RUN set -eux; \
    curl -fsSL "https://github.com/ortic/php-pdo-duckdb/archive/refs/heads/main.tar.gz" | tar xz -C /tmp; \
    cd /tmp/php-pdo-duckdb-main; \
    for cfg in /usr/bin/php-config[0-9].[0-9]; do \
        ver="$(basename "$cfg" | sed 's/php-config//')"; \
        pz="/usr/bin/phpize${ver}"; \
        [ -x "$pz" ] || continue; \
        echo ">>> building pdo_duckdb for PHP ${ver}"; \
        PHPIZE="$pz" PHP_CONFIG="$cfg" DUCKDB_VERSION="${DUCKDB_VERSION}" ./scripts/install.sh; \
    done; \
    rm -rf /tmp/php-pdo-duckdb-main

DOCKER;
    }
}
